### ISSUE TITLE
Translations would be great

### ISSUE THREAD

**Issue by mvdberge** [PhieF/CarnetElectron#13]
I would be willing to provide a German translation, but as far as I can see, the code base first needs to support that.

**Comment by Picard0147** [comment]
Yes, possibility of translation would be great. If provide files with strings to translate I can make Czech translation.

**Comment by Vistaus** [comment]
Yes, it would sure be great. I would provide a Dutch translation :)

**Comment by PhieF** [comment]
Hi !

It's now possible to translate at
https://weblate.lostpod.me

Carnet/HTML is the right project for the electron and nextcloud version !

Thanks for helping ! 
BTW Vistaus I've added your name here if you don't mind https://github.com/PhieF/CarnetDocumentation/blob/master/THANKS.md
