### ISSUE TITLE
Settings do not work

### ISSUE THREAD

**Issue by Salamandar** [PhieF/CarnetElectron#20]
The appimage seems broken. None of the settings buttons work, and going back to the explorer view from the settings view shows a blank view.

Nothing in the logs :(

**Comment by bowmasters** [comment]
there's a PR open for this in the other repository: https://framagit.org/PhieF/CarnetElectron/merge_requests/1

 I'm not sure which repo is the primary, github or the gitlab instance on framagit

**Comment by PhieF** [comment]
Hi,

sorry to be that late

the pull request has been merged, thanks
