### ISSUE TITLE
Error while importing notes from Google Keep

### ISSUE THREAD

**Issue by kauron** [PhieF/CarnetElectron#6]
Hi, I've just gotten an exception while trying to import notes from Keep. The import itself doesn't advance at all, and after a while (~20min) it threw the following exception:

```
Uncaught Exception:
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at /tmp/.mount_carnetoxue7t/app/resources/app.asar/recent/recent_db_manager.js:205:48
    at /tmp/.mount_carnetoxue7t/app/resources/app.asar/recent/recent_db_manager.js:16:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

I'm using the AppImage64 bit version downloaded from [here][1], as listed in your main [repo][2], in Arch Linux.

[1]: https://qn.phie.ovh/binaries/desktop/current64.AppImage
[2]: https://github.com/PhieF/CarnetDocumentation

**Comment by PhieF** [comment]
Thanks for reporting, I will have a look soon. Lot of stuffs to change before that :(

**Comment by ibeardslee** [comment]
Are there any interesting 'hacks' that could be done in the meantime?
I have the "pick directory" that just never goes away when I try to do an import.

**Comment by pierre-flande** [comment]
> Are there any interesting 'hacks' that could be done in the meantime?
> I have the "pick directory" that just never goes away when I try to do an import.

I have exactly the same issue. 
Does anyone have an idea of what is happening behind the scenes and how to make that import possible?
