### ISSUE TITLE
AppImage 1-11-18

### ISSUE THREAD

**Issue by justinesmithies** [PhieF/CarnetElectron#9]
The current daily AppImage doesn't display any of the notes created with with the Nextcloud instance or the Latest 06-11-18 Android Image. I can create a new note using the Linux AppImage but it does not display in the Recents or browser.
You can only view the notes using Android or NextCloud.
I have tried removing the hidden Carnet folder in .Config and re running the app fresh but it still does not display the notes.

**Comment by PhieF** [comment]
You mean it doesn't sync ?

**Comment by justinesmithies** [comment]
I could be that it's not syncing ???? Just the right hand side where the notes should be visible is just blank.

**Comment by PhieF** [comment]
OK, and when you click on one of these notes, are they editable ? (do it on a note you can loose)

By the way : be careful with daily images and daily app, they can be really really buggy

**Comment by justinesmithies** [comment]
No using the AppImage I cannot see or click on anything it's just a white background where they should be. I can edit them in the Nextcloud and Android instances though.

It's okay I like bleeding edge and I'm all for testing .

**Comment by justinesmithies** [comment]
That fixed it ! Thank you ;-)

**Comment by PhieF** [comment]
Thanks to you :) I didn't even noticed this bug and this was in the stable version, I will have to release a new version sooner to fix it
